- name: Process and Push Images
  run: |
    # 定义目标路径（确保无多余斜杠）
    TARGET_PREFIX="${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/${{ env.ALIYUN_REPO_NAME }}"
    TARGET_PREFIX=$(echo "$TARGET_PREFIX" | sed 's|//|/|g; s|/$||')

    while IFS= read -r line; do
      [[ -z "$line" ]] || [[ "$line" =~ ^# ]] && continue

      # 解析镜像名称和标签
      src_image=$(echo "$line" | awk '{print $NF}' | sed 's/@sha256:.*//')
      image_name=$(echo "$src_image" | awk -F: '{print $1}')
      image_tag=$(echo "$src_image" | awk -F: '{print $2}')

      # 生成目标路径（关键：使用冒号分隔标签）
      target_image="${TARGET_PREFIX}:${image_name}-${image_tag}"
      echo "推送路径：${target_image}"

      # 执行Docker操作
      docker pull "$src_image"
      docker tag "$src_image" "$target_image"
      docker push "$target_image"
    done < ./images.txt
