name: Aliyun Image Push

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "crpi-qdxa7r1jpsbtqqwp.cn-shenzhen.personal.cr.aliyuncs.com"
  ALIYUN_NAME_SPACE: "docker20250406/k8s"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  push-image:
    name: Push to Aliyun
    runs-on: ubuntu-latest

    steps:
    # ========== 1. 检出代码 ==========
    - name: Checkout Code
      uses: actions/checkout@v4

    # ========== 2. 登录阿里云（修复版） ==========
    - name: Login to Aliyun
      run: |
        echo "正在登录阿里云容器镜像服务..."
        echo "$ALIYUN_REGISTRY_PASSWORD" | docker login \
          -u "$ALIYUN_REGISTRY_USER" \
          --password-stdin "$ALIYUN_REGISTRY"
      env:  # 显式传递环境变量
        ALIYUN_REGISTRY: ${{ env.ALIYUN_REGISTRY }}
        ALIYUN_REGISTRY_USER: ${{ env.ALIYUN_REGISTRY_USER }}
        ALIYUN_REGISTRY_PASSWORD: ${{ env.ALIYUN_REGISTRY_PASSWORD }}

    # ========== 3. 镜像推送逻辑 ==========
    - name: Process and Push Images
      run: |
        TARGET_PREFIX="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE"

        while IFS= read -r line; do
          [[ -z "$line" ]] || [[ "$line" =~ ^# ]] && continue

          src_image=$(echo "$line" | awk '{print $NF}' | sed 's/@sha256:.*//')
          # ...（保持原有镜像处理逻辑不变）
        done < ./images.txt
