name: Aliyun Image Push

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"  # 例：crpi-xxx.cn-shenzhen.personal.cr.aliyuncs.com
  ALIYUN_NAMESPACE: "${{ secrets.ALIYUN_NAMESPACE }}"  # 例：docker20250406
  ALIYUN_REPO_NAME: "k8s"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      run: |
        echo "${{ env.ALIYUN_REGISTRY_PASSWORD }}" | docker login \
          --username "${{ env.ALIYUN_REGISTRY_USER }}" \
          --password-stdin "${{ env.ALIYUN_REGISTRY }}"

    - name: Push Images
      run: |
        TARGET="${ALIYUN_REGISTRY}/${ALIYUN_NAMESPACE}/${ALIYUN_REPO_NAME}"
        echo "推送目标: ${TARGET}"

        while IFS= read -r line; do
          [[ -z "$line" || "$line" =~ ^# ]] && continue

          # 提取镜像名和标签
          src_image=$(echo "$line" | awk '{print $NF}' | sed 's/@sha256:.*//')
          tag=$(echo "$src_image" | awk -F: '{print $2}')
          
          # 生成安全标签
          safe_tag=$(echo "$src_image" | sed -E 's#[^a-zA-Z0-9._-]#_#g')
          target_image="${TARGET}:${safe_tag}"

          echo "推送镜像: $src_image → $target_image"
          
          docker pull "$src_image"
          docker tag "$src_image" "$target_image"
          docker push "$target_image"
          docker rmi "$src_image" "$target_image" || true

        done < ./images.txt
