name: Aliyun Image Push

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "crpi-qdxa7r1jpsbtqqwp.cn-shenzhen.personal.cr.aliyuncs.com"
  ALIYUN_NAMESPACE: "docker20250406/k8s"
  ALIYUN_USER: "${{ secrets.ALIYUN_USER }}"          # 必须使用AccessKey ID
  ALIYUN_PASSWORD: "${{ secrets.ALIYUN_PASSWORD }}"  # 必须使用AccessKey Secret

jobs:
  push-image:
    name: Push to Aliyun
    runs-on: ubuntu-latest

    steps:
    # ========== 1. 登录阿里云 ==========
    - name: Login to Aliyun
      run: echo "$ALIYUN_PASSWORD" | docker login -u "$ALIYUN_USER" --password-stdin "$ALIYUN_REGISTRY"

    # ========== 2. 检出代码 ==========
    - name: Checkout Code
      uses: actions/checkout@v4

    # ========== 3. 推送镜像 ==========
    - name: Push Images
      run: |
        while IFS= read -r line; do
          [[ -z "$line" ]] || [[ "$line" =~ ^# ]] && continue

          src_image=$(echo "$line" | awk '{print $NF}')
          target_image="$ALIYUN_REGISTRY/$ALIYUN_NAMESPACE:$(echo "$src_image" | awk -F: '{print $2}')"

          echo "====== Pushing: $src_image => $target_image ======"
          docker pull "$src_image"
          docker tag "$src_image" "$target_image"
          docker push "$target_image"
          docker rmi "$src_image" "$target_image"
        done < ./images.txt
