name: DockerHub to Aliyun Mirror

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "crpi-qdxa7r1jpsbtqqwp.cn-shenzhen.personal.cr.aliyuncs.com"
  ALIYUN_NAMESPACE: "docker20250406/k8s"  # k8s是仓库名称
  ALIYUN_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  mirror-images:
    name: Mirror Images
    runs-on: ubuntu-latest

    steps:
    # ========== 环境初始化 ==========
    - name: Initialize Docker
      run: |
        sudo rm -rf /var/lib/docker/*
        sudo mkdir -p /etc/docker
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        sleep 5

    # ========== 安全登录 ==========
    - name: Login to Aliyun
      run: |
        echo "$ALIYUN_PASSWORD" | docker login -u $ALIYUN_USER --password-stdin $ALIYUN_REGISTRY

    # ========== 代码检出 ==========
    - name: Checkout Code
      uses: actions/checkout@v4

    # ========== 镜像同步核心逻辑 ==========
    - name: Mirror Images
      run: |
        TARGET_PREFIX="$ALIYUN_REGISTRY/$ALIYUN_NAMESPACE"

        while IFS= read -r line; do
          [[ -z "$line" ]] || [[ "$line" =~ ^# ]] && continue

          # 处理平台参数（修复grep兼容性问题）
          platform_arg=$(echo "$line" | sed -n 's/.*--platform \([^ ]*\).*/\1/p')
          original_line=$(echo "$line" | sed 's/--platform [^ ]*//g')

          # 处理原始镜像名称
          original_image=$(echo "$original_line" | awk '{print $NF}' | sed 's/@sha256:.*//')
          if [[ ! "$original_image" =~ / ]]; then
            original_image="docker.io/library/$original_image"
          elif [[ ! "$original_image" =~ ^docker.io/ ]]; then
            original_image="docker.io/$original_image"
          fi

          # 转换镜像名称（关键修正：移除所有层级）
          converted_image=$(echo "$original_image" | sed 's|docker.io/||g; s|/|_|g; s|^library_||')
          
          # 生成目标镜像名称
          target_image="$TARGET_PREFIX/$converted_image"
          
          # 添加平台后缀
          if [ -n "$platform_arg" ]; then
            platform_suffix="-$(echo "$platform_arg" | tr '/' '_')"
            target_image="${target_image}${platform_suffix}"
          fi

          echo "====== Syncing: $original_image => $target_image ======"
          
          # 拉取镜像
          pull_cmd="docker pull"
          [ -n "$platform_arg" ] && pull_cmd="$pull_cmd --platform $platform_arg"
          $pull_cmd $original_image || exit 1

          # 推送镜像
          docker tag $original_image $target_image
          docker push $target_image || exit 1

          # 清理镜像
          docker rmi $original_image $target_image || true

        done < ./images.txt

    # ========== 最终清理 ==========
    - name: Cleanup
      run: |
        docker system prune -af
