name: Aliyun Image Push

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"  # 示例：crpi-xxx.cn-shenzhen.personal.cr.aliyuncs.com
  ALIYUN_NAMESPACE: "${{ secrets.ALIYUN_NAMESPACE }}"  # 必须配置命名空间
  ALIYUN_REPO_NAME: "k8s"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      run: |
        echo "${{ env.ALIYUN_REGISTRY_PASSWORD }}" | docker login \
          --username "${{ env.ALIYUN_REGISTRY_USER }}" \
          --password-stdin "${{ env.ALIYUN_REGISTRY }}"

    - name: Push Images
      run: |
        # 核心修复：强制路径格式校验
        REGISTRY=$(echo "${ALIYUN_REGISTRY}" | sed 's:/*$::')  # 去除末尾斜杠
        NAMESPACE=$(echo "${ALIYUN_NAMESPACE}" | sed 's:^/*::;s:/*$::')  # 去除首尾斜杠
        REPO=$(echo "${ALIYUN_REPO_NAME}" | sed 's:^/*::;s:/*$::')  # 去除首尾斜杠

        # 构建完整仓库路径
        TARGET="${REGISTRY}/${NAMESPACE}/${REPO}"
        echo "推送路径模板: ${TARGET}:<tag>"

        while IFS= read -r line; do
          [[ -z "$line" || "$line" =~ ^# ]] && continue

          # 提取镜像信息
          src_image=$(echo "$line" | awk '{print $NF}' | sed 's/@sha256:.*//')
          image_repo=$(echo "$src_image" | awk -F: '{print $1}')
          image_tag=$(echo "$src_image" | awk -F: '{print $2}')

          # 生成安全标签（符合 Docker 规范）
          safe_tag=$(echo "${image_repo}-${image_tag}" | sed -E 's/[^a-zA-Z0-9._-]/_/g')

          # 构建目标镜像地址
          target_image="${TARGET}:${safe_tag}"
          echo "推送目标: $target_image"

          # 拉取/推送/清理
          docker pull "$src_image"
          docker tag "$src_image" "$target_image"
          docker push "$target_image"
          docker rmi "$src_image" "$target_image" || true

        done < ./images.txt
